[#414] Still trying to fix `AttributeError: partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)` on GitHub actions.